cd $PSScriptRoot
cd TOJ-Implementations/ARTOJ/Assets/artos-core
git pull
cd $PSScriptRoot
cd TOJ-Implementations/RTOJ/Assets/artos-core
git pull
cd $PSScriptRoot
cd TOJ-Implementations/VRTOJ/Assets/artos-core
git pull