name: Unity Builds

on: [push, pull_request]

jobs:
  build:
    name: Build my project
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: clone submodule
        uses: actions/checkout@v2
        with:
          repository: caiusno1/artos-core
          path: TOJ-Implementations/VRTOJ/Assets
          ssh-key: ${{ secrets.SUBMODULE_SSH_KEY }}
          persist-credentials: false
      
      - name: clone submodule
        uses: actions/checkout@v2
        with:
          repository: caiusno1/artos-core
          path: TOJ-Implementations/ARTOJ/Assets/artos-core
          ssh-key: ${{ secrets.SUBMODULE_SSH_KEY }}
          persist-credentials: false

      # Cache
      - uses: actions/cache@v2
        with:
          path: TOJ-Implementations/VRTOJ/Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Build
      - name: Build VRTOJ
        uses: game-ci/unity-builder@v2
        env:
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: TOJ-Implementations/VRTOJ
          targetPlatform: Android

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build

      # Return License
      - name: Return license
        uses: game-ci/unity-return-license@v2
        if: always()